import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Saira } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";

const font = Saira({
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={` ${font.className} mx-1 my-1`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
